import type { CustomYearSetting } from "@/types/schedule";

// 非公式イベント定義（impl/custom.js を移植）
export const CUSTOM_SETTING: Record<string, CustomYearSetting> = {
  "2024": {
    events: [
      {
        title: "ProCEDEC 2024",
        hash_tag: "ProCEDEC",
        room_no: "L.A.S.T ワールドポーターズ店",
        day_index: 2,
        start_time: "19:45",
        end_time: "21:45",
        detail_url: "https://peatix.com/event/4060671/",
      },
      {
        title: "CEDEC・GDGD #2024（CEDEC3日目ゲームデザイン懇親会）",
        room_no: "さかえや 横浜みなとみらい本店",
        day_index: 2,
        start_time: "19:45",
        end_time: "21:45",
        detail_url: "https://peatix.com/event/4077809",
      },
      {
        title: "Artists Meet Technicals 2024 supported by TA Night",
        room_no: "FISHERMAN'S MARKET",
        day_index: 2,
        start_time: "19:00",
        end_time: "21:00",
        detail_url: "https://artistsmeetstechnicals.doorkeeper.jp/events/176019",
      },
      {
        title: "UI CEDEC 2024【UI懇親会】",
        hash_tag: "UICEDEC",
        room_no: "パセラリゾーツ横浜関内店",
        day_index: 2,
        start_time: "19:30",
        end_time: "22:00",
        detail_url: "https://peatix.com/event/4081264",
      },
      {
        title: "CEDECON2024",
        room_no: "パセラリゾーツ横浜関内店",
        day_index: 2,
        start_time: "19:45",
        end_time: "22:00",
        detail_url: "https://peatix.com/event/4081195",
      },
      {
        title: "教育CEDEC 2024",
        room_no: "~ 検討中 ~",
        day_index: 2,
        start_time: "19:00",
        end_time: "22:00",
        detail_url: "https://peatix.com/event/4082927",
      },
    ],
  },
  "2023": {
    events: [
      {
        title: "ProCEDEC 2023",
        hash_tag: "ProCEDEC",
        room_no: "健康中華 青蓮 みなとみらい店",
        day_index: 2,
        start_time: "19:30",
        end_time: "22:30",
        detail_url: "https://peatix.com/event/3640537",
      },
      {
        title: "CEDEC・GDGD #2023",
        room_no: "橙家 みなとみらい東急スクエア店",
        day_index: 2,
        start_time: "19:00",
        end_time: "21:00",
        detail_url: "https://cedecgdgd2023.peatix.com/",
      },
      {
        title: "Artists Meet Technicals 2023 supported by TA Night",
        room_no: "J PASTA terrace クイーンズスクエア横浜店",
        day_index: 2,
        start_time: "19:30",
        end_time: "21:00",
        detail_url: "https://www.creativevillage.ne.jp/category/event-list/138051/",
      },
      {
        title: "【裏CEDEC】UI CEDEC 2023",
        room_no: "グレースバリ 横浜 関内店",
        day_index: 2,
        start_time: "19:30",
        end_time: "23:00",
        detail_url: "https://www.facebook.com/events/309432671558065",
      },
      {
        title: "CEDECON2023",
        room_no: "パセラリゾーツ横浜関内店",
        day_index: 2,
        start_time: "19:45",
        end_time: "22:00",
        detail_url: "https://peatix.com/event/3676741",
      },
    ],
  },
  "2022": {
    events: [
      {
        title: "Artists Meets Technicals 2022 Online supported by TA Night",
        room_no: "オンライン",
        day_index: 2,
        start_time: "19:30",
        end_time: "21:30",
        detail_url: "https://www.creativevillage.ne.jp/115551",
      },
      {
        title: "『VRプロダクト開発ラウンドテーブル』に連動した非公式の懇親イベント",
        room_no: "VRChatのプライベートインスタンス",
        day_index: 1,
        start_time: "22:30",
        end_time: "24:00",
        detail_url: "https://twitter.com/nkjzm/status/1561308056822358016",
      },
      {
        title: "感想戦・深夜の部",
        room_no: "Discord",
        day_index: 1,
        start_time: "22:00",
        end_time: "24:00",
        html: "Discord「CEDEC2022コミュニティ」内で実施します<br/>参加者の方は、CEDECマイページ内、催事紹介からご参加ください。",
      },
      {
        title: "ProCEDEC",
        hash_tag: "ProCEDEC",
        room_no: "Discord",
        day_index: 2,
        start_time: "19:30",
        end_time: "24:00",
        html: "Discord「CEDEC2022コミュニティ」内で実施します<br/>参加者の方は、CEDECマイページ内、催事紹介からご参加ください。<br/>※時間の許す限りゆるく開催<br/>※過去のProCEDECと関わりはありません",
      },
    ],
  },
};
