import type { CustomYearSetting } from "@/types/schedule";

// 非公式イベント定義（impl/custom.js を移植）
export const CUSTOM_SETTING: Record<string, CustomYearSetting> = {
  "2019": {
    events: [
      {
        title: "Artists Meets Technicals 2019",
        room_no: "みなとみらい BLUE LIGHT BEER GARDEN",
        day_index: 2,
        start_time: "19:30",
        end_time: "22:00",
        detail_url: "https://artistsmeetstechnicals.doorkeeper.jp/events/95034",
      },
      {
        title: "ProCEDEC2019",
        hash_tag: "ProCEDEC",
        room_no: "ニューヨークグランドキッチン",
        day_index: 2,
        start_time: "19:30",
        end_time: "22:30",
        detail_url: "https://peatix.com/event/1160115",
      },
      {
        title: "UI CEDEC 2019",
        hash_tag: "UICEDEC",
        room_no: "未定",
        day_index: 2,
        start_time: "19:30",
        end_time: "21:30",
        detail_url: "https://ui-cedec.connpass.com/event/143681/",
      },
      {
        title: "裏 CEDEC 2019",
        room_no: "のげ",
        day_index: 2,
        start_time: "19:30",
        end_time: "21:30",
        detail_url: "https://ura-cedec.com/",
        html: '<font color="#FF4500">時間詳細不明</font>',
      },
      {
        title: "音 CEDEC 2019",
        room_no: "不明",
        day_index: 2,
        start_time: "19:30",
        end_time: "21:30",
        html: '<font color="#FF4500">招待制<br/>場所・時間ともに詳細不明</font>',
      },
      {
        title: "CEDECON 2019",
        hash_tag: "cedecon",
        room_no: "パセラリゾーツ 横浜関内 グレースバリ 3F",
        day_index: 2,
        start_time: "19:30",
        end_time: "22:00",
        detail_url: "https://cedecon2019.peatix.com/",
      },
      {
        title: "AiCEDEC2019",
        hash_tag: "AiCEDEC,AiCEDEC2019",
        room_no: "横浜モノリス",
        day_index: 2,
        start_time: "19:45",
        end_time: "21:45",
        detail_url: "https://passmarket.yahoo.co.jp/event/show/detail/01pyh810ex3u6.html",
      },
      {
        title: "CEDEC・GDGD 2019",
        room_no: "みなとみらい近辺の居酒屋",
        day_index: 2,
        start_time: "19:30",
        end_time: "22:30",
        detail_url: "https://peatix.com/event/1307117",
      },
    ],
  },
  "2018": {
    events: [
      {
        title: "ProCEDEC2018",
        hash_tag: "ProCEDEC",
        room_no: "ニューヨークグランドキッチン",
        day_index: 2,
        start_time: "19:30",
        end_time: "22:30",
        detail_url: "https://procedec2018.peatix.com/",
      },
      {
        title: "Artists Meets Technicals 2018",
        room_no: "サンタモニカ・サードストリート ミートテラス",
        day_index: 2,
        start_time: "20:00",
        end_time: "22:00",
        detail_url: "https://artistsmeetstechnicals.doorkeeper.jp/events/77430",
      },
      {
        title: "UI CEDEC 2018",
        hash_tag: "UICEDEC",
        room_no: "HUB Colette・Mare みなとみらい店",
        day_index: 2,
        start_time: "19:30",
        end_time: "21:30",
        detail_url: "https://ui-cedec.connpass.com/event/96867/",
      },
      {
        title: "裏 CEDEC 2018",
        room_no: "のげ（ちょっと遠いので、時間厳守）",
        day_index: 2,
        start_time: "19:30",
        end_time: "21:30",
        detail_url: "https://ura-cedec.com/",
      },
      {
        title: "音 CEDEC 2018",
        room_no: "不明",
        day_index: 2,
        start_time: "19:30",
        end_time: "21:30",
        html: '<font color="#FF4500">招待制<br/>場所・時間ともに詳細不明</font>',
      },
      {
        title: "CEDECON 2018",
        hash_tag: "cedecon",
        room_no: "HUB Colette・Mare みなとみらい店",
        day_index: 2,
        start_time: "19:30",
        end_time: "21:30",
        detail_url: "https://cedecon2018.peatix.com/",
      },
      {
        title: "AiCEDEC2018",
        hash_tag: "AiCEDEC",
        room_no: "横浜モノリス",
        day_index: 2,
        start_time: "19:45",
        end_time: "21:45",
        detail_url: "https://aicedec2018.peatix.com/",
      },
      {
        title: "第1回 cedec女子会",
        room_no: "SANTA MONICA 3rd st. MEAT TERRACE",
        day_index: 0,
        start_time: "19:00",
        end_time: "22:00",
        detail_url: "https://www.facebook.com/events/507327916393384/",
      },
    ],
  },
  "2024": {
    events: [
      {
        title: "ProCEDEC 2024",
        hash_tag: "ProCEDEC",
        room_no: "L.A.S.T ワールドポーターズ店",
        day_index: 2,
        start_time: "19:45",
        end_time: "21:45",
        detail_url: "https://peatix.com/event/4060671/",
      },
      {
        title: "CEDEC・GDGD #2024（CEDEC3日目ゲームデザイン懇親会）",
        room_no: "さかえや 横浜みなとみらい本店",
        day_index: 2,
        start_time: "19:45",
        end_time: "21:45",
        detail_url: "https://peatix.com/event/4077809",
      },
      {
        title: "Artists Meet Technicals 2024 supported by TA Night",
        room_no: "FISHERMAN'S MARKET",
        day_index: 2,
        start_time: "19:00",
        end_time: "21:00",
        detail_url: "https://artistsmeetstechnicals.doorkeeper.jp/events/176019",
      },
      {
        title: "UI CEDEC 2024【UI懇親会】",
        hash_tag: "UICEDEC",
        room_no: "パセラリゾーツ横浜関内店",
        day_index: 2,
        start_time: "19:30",
        end_time: "22:00",
        detail_url: "https://peatix.com/event/4081264",
      },
      {
        title: "CEDECON2024",
        room_no: "パセラリゾーツ横浜関内店",
        day_index: 2,
        start_time: "19:45",
        end_time: "22:00",
        detail_url: "https://peatix.com/event/4081195",
      },
      {
        title: "教育CEDEC 2024",
        room_no: "~ 検討中 ~",
        day_index: 2,
        start_time: "19:00",
        end_time: "22:00",
        detail_url: "https://peatix.com/event/4082927",
      },
    ],
  },
  "2023": {
    events: [
      {
        title: "ProCEDEC 2023",
        hash_tag: "ProCEDEC",
        room_no: "健康中華 青蓮 みなとみらい店",
        day_index: 2,
        start_time: "19:30",
        end_time: "22:30",
        detail_url: "https://peatix.com/event/3640537",
      },
      {
        title: "CEDEC・GDGD #2023",
        room_no: "橙家 みなとみらい東急スクエア店",
        day_index: 2,
        start_time: "19:00",
        end_time: "21:00",
        detail_url: "https://cedecgdgd2023.peatix.com/",
      },
      {
        title: "Artists Meet Technicals 2023 supported by TA Night",
        room_no: "J PASTA terrace クイーンズスクエア横浜店",
        day_index: 2,
        start_time: "19:30",
        end_time: "21:00",
        detail_url: "https://www.creativevillage.ne.jp/category/event-list/138051/",
      },
      {
        title: "【裏CEDEC】UI CEDEC 2023",
        room_no: "グレースバリ 横浜 関内店",
        day_index: 2,
        start_time: "19:30",
        end_time: "23:00",
        detail_url: "https://www.facebook.com/events/309432671558065",
      },
      {
        title: "CEDECON2023",
        room_no: "パセラリゾーツ横浜関内店",
        day_index: 2,
        start_time: "19:45",
        end_time: "22:00",
        detail_url: "https://peatix.com/event/3676741",
      },
    ],
  },
  "2022": {
    events: [
      {
        title: "Artists Meets Technicals 2022 Online supported by TA Night",
        room_no: "オンライン",
        day_index: 2,
        start_time: "19:30",
        end_time: "21:30",
        detail_url: "https://www.creativevillage.ne.jp/115551",
      },
      {
        title: "『VRプロダクト開発ラウンドテーブル』に連動した非公式の懇親イベント",
        room_no: "VRChatのプライベートインスタンス",
        day_index: 1,
        start_time: "22:30",
        end_time: "24:00",
        detail_url: "https://twitter.com/nkjzm/status/1561308056822358016",
      },
      {
        title: "感想戦・深夜の部",
        room_no: "Discord",
        day_index: 1,
        start_time: "22:00",
        end_time: "24:00",
        html: "Discord「CEDEC2022コミュニティ」内で実施します<br/>参加者の方は、CEDECマイページ内、催事紹介からご参加ください。",
      },
      {
        title: "ProCEDEC",
        hash_tag: "ProCEDEC",
        room_no: "Discord",
        day_index: 2,
        start_time: "19:30",
        end_time: "24:00",
        html: "Discord「CEDEC2022コミュニティ」内で実施します<br/>参加者の方は、CEDECマイページ内、催事紹介からご参加ください。<br/>※時間の許す限りゆるく開催<br/>※過去のProCEDECと関わりはありません",
      },
    ],
  },
};
